Refactor Javadoc deployment workflow to separate fetching, building, and committing steps

diff --git a/.github/workflows/build-and-deploy-javadoc.yml b/.github/workflows/build-and-deploy-javadoc.yml
--- a/.github/workflows/build-and-deploy-javadoc.yml
+++ b/.github/workflows/build-and-deploy-javadoc.yml
@@ -1,4 +1,4 @@
-name: Build And Commit Javadoc
+name: Update Javadoc
 
 on:
   schedule:
@@ -6,34 +6,13 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-and-commit-javadoc:
+  fetch-latest-release:
     runs-on: ubuntu-latest
 
     env:
       REPO: "processing/processing4"
-      REMOTE_URL: "https://github.com/processing/processing4.git"
 
     steps:
-    - name: Checkout gh-pages branch
-      uses: actions/checkout@v3
-      with:
-        ref: gh-pages
-
-    - name: Set up JDK 17
-      uses: actions/setup-java@v3
-      with:
-        distribution: 'adopt'
-        java-version: '17'
-
-    - name: Ensure Ant is installed
-      run: |
-        if ! command -v ant &> /dev/null; then
-          echo "Ant not found, installing..."
-          sudo apt-get update && sudo apt-get install -y ant
-        else
-          echo "Ant is already installed"
-        fi
-
     - name: Get the latest release tag and commit SHA
       id: get-commit-sha
       run: |
@@ -61,6 +40,34 @@ jobs:
         echo "Commit SHA: $commit_sha"
         echo "commit_sha=$commit_sha" >> $GITHUB_ENV
 
+  build-javadoc:
+    runs-on: ubuntu-latest
+    needs: fetch-latest-release
+
+    env:
+      REMOTE_URL: "https://github.com/processing/processing4.git"
+
+    steps:
+    - name: Checkout gh-pages branch
+      uses: actions/checkout@v3
+      with:
+        ref: gh-pages
+
+    - name: Set up JDK 17
+      uses: actions/setup-java@v3
+      with:
+        distribution: 'adopt'
+        java-version: '17'
+
+    - name: Ensure Ant is installed
+      run: |
+        if ! command -v ant &> /dev/null; then
+          echo "Ant not found, installing..."
+          sudo apt-get update && sudo apt-get install -y ant
+        else
+          echo "Ant is already installed"
+        fi
+
     - name: Fetch and checkout the specific commit
       run: |
         git init processing4
@@ -83,6 +90,16 @@ jobs:
     - name: Clean up the processing4 directory
       run: |
         rm -rf processing4/
+
+  commit-javadoc:
+    runs-on: ubuntu-latest
+    needs: build-javadoc
+
+    steps:
+    - name: Checkout gh-pages branch
+      uses: actions/checkout@v3
+      with:
+        ref: gh-pages
 
     - name: Commit and Push changes to gh-pages if any changes exist
       run: |
